apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/engineer/projects/J16/media-server/deluge/config

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: deluge-config

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: lscr.io/linuxserver/deluge:latest
          ports:
            - containerPort: 8112
          volumeMounts:
            - name: deluge-config
              mountPath: /config
            - name: jellyfin-media
              mountPath: /downloads
            - name: jackett-blackhole
              mountPath: /watch
      volumes:
        - name: deluge-config
          persistentVolumeClaim:
            claimName: deluge-config
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-media
        - name: jackett-blackhole
          persistentVolumeClaim:
            claimName: jackett-blackhole

--- 

apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  selector:
    app: deluge
  type: NodePort
  ports:
    - port: 8112
      targetPort: 8112
      nodePort: 30112